version: '3.8'

services:
  code-reviewer:
    build: .
    container_name: code-reviewer
    restart: unless-stopped
    
    # Environment configuration
    env_file:
      - .env
    
    # Environment variables (can override .env file)
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - POLL_INTERVAL=${POLL_INTERVAL:-60}
      - SOUND_ENABLED=${SOUND_ENABLED:-false}
      - DRY_RUN=${DRY_RUN:-false}
      - DATABASE_PATH=data/reviews.db
    
    # Volume mounts for persistent data
    volumes:
      # Persistent database and application data
      - ./data:/app/data
      
      # Custom prompts (optional)
      - ./prompts:/app/prompts
      
      # Custom configuration files (optional)  
      - ./config:/app/config
      
      # Logs directory (optional)
      - ./logs:/app/logs
      
      # Custom sound files (optional)
      # - ./sounds:/app/sounds
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; sqlite3.connect('data/reviews.db').execute('SELECT 1').fetchone()"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Network mode (default)
    network_mode: bridge
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Read-only root filesystem (with writable volumes)
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
    
    # Labels for organization
    labels:
      - "com.example.application=code-reviewer"
      - "com.example.version=1.0.0"
      - "com.example.description=Automated GitHub PR code review system"

# Optional: Add a volume for shared data if running multiple instances
volumes:
  code_reviewer_data:
    driver: local
    
# Optional: Custom network configuration
networks:
  default:
    name: code-reviewer-network